default_language_version:
  python: python3
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--fix"]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==23.7.0
        args: [ "--line-length", "120", "--target-version", "py39"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    - id: codespell
      additional_dependencies:
      - tomli
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [ "--maxkb=512" ]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
        args: ["--fix=auto"]
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [--config=pyproject.toml]
        exclude: ^(docs/conf.py|test/) # copy from pyproject.toml
        additional_dependencies:
         - numpy==2.2.4
         - types-python-dateutil==2.8.19.14
         - types-requests==2.31.0.10
         - types-pytz==2025.2.0.20250326
         - attrs==25.3.0
         - cryptography==44.0.2
         - python-dotenv==1.0.1
  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.2
    hooks:
      -   id: poetry-check
      -   id: poetry-lock
